name: Student CI (Build & Test)

on:
  push:
  pull_request:

jobs:
  build-java:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build & test Java code
        run: |
          ./gradlew fetchNatives
          ./gradlew build
